const C={income:["Salary","Bonus","Freelance","Interest","Other"],expense:["Food","Groceries","Rent","Electricity","Water","Travel","Fuel","Shopping","Medical","Education","Entertainment","Bills","Other"]};
let data=JSON.parse(localStorage.getItem("salaryManager")||'{"entries":[],"budget":0}');
let view="home", addType="expense", period="month", date=new Date();
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s||"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const save=()=>localStorage.setItem("salaryManager",JSON.stringify(data));
const fmtDate=d=>new Date(d).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
function balance(){return data.entries.reduce((a,e)=>a+(e.type==="income"?e.amount:-e.amount),0)}
function monthEntries(d=new Date()){return data.entries.filter(e=>{let x=new Date(e.date);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()})}
function weekEntries(d=new Date()){let x=new Date(d);let day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);let end=new Date(x);end.setDate(end.getDate()+7);return data.entries.filter(e=>{let y=new Date(e.date);return y>=x&&y<end})}
function entryRow(e){let sign=e.type==="income"?"+":"−";return `<div class="row"><div><b>${esc(e.category||e.type)}</b><div class="muted">${esc(e.person||e.place||"")}${e.note?" • "+esc(e.note):""}</div><small>${fmtDate(e.date)}${e.dueDate?" • Due "+fmtDate(e.dueDate):""}</small></div><b class="${e.type==="income"?"income":""}">${sign}${money(e.amount)}</b></div>`}
function nav(){return `<div class="nav">${["home","calendar","budget","all"].map(v=>`<button class="${view===v?"active":""}" onclick="setView('${v}')">${v==="home"?"⌂":v==="calendar"?"▣":v==="budget"?"◒":"☷"}<br><small>${v[0].toUpperCase()+v.slice(1)}</small></button>`).join("")}</div>`}
function render(){let app=document.getElementById("app");app.innerHTML=`<div class="app">${view==="home"?home():view==="calendar"?calendar():view==="budget"?budget():all()}${nav()}</div>`}
function home(){let me=monthEntries(),inc=me.filter(e=>e.type==="income").reduce((a,e)=>a+e.amount,0),ex=me.filter(e=>e.type==="expense").reduce((a,e)=>a+e.amount,0),lent=me.filter(e=>e.type==="lent").reduce((a,e)=>a+e.amount,0),debt=me.filter(e=>e.type==="debt").reduce((a,e)=>a+e.amount,0);return `<div class="top"><div class="title">Salary Manager</div><div class="muted">${new Date().toLocaleDateString("en-IN",{month:"long",year:"numeric"})}</div></div><div class="balance"><small>Current balance</small><strong>${money(balance())}</strong></div><div class="grid"><button class="quick income" onclick="add('income')"><span>↓</span>Income</button><button class="quick expense" onclick="add('expense')"><span>↑</span>Expense</button><button class="quick lent" onclick="add('lent')"><span>↗</span>Lent</button><button class="quick debt" onclick="add('debt')"><span>▣</span>Debt</button></div><div class="card"><h3>This month</h3><div class="row"><span>Income</span><b class="income">${money(inc)}</b></div><div class="row"><span>Expenses</span><b>${money(ex)}</b></div><div class="row"><span>Lent</span><b>${money(lent)}</b></div><div class="row"><span>Debt</span><b>${money(debt)}</b></div></div>${data.budget?`<div class="card"><b>Monthly expense budget</b><div style="margin:10px 0">${money(ex)} of ${money(data.budget)}</div><div class="bar"><i style="width:${Math.min(100,ex/data.budget*100)}%"></i></div><small class="muted">${money(Math.max(0,data.budget-ex))} remaining</small></div>`:""}<div class="card"><h3>Recent</h3>${data.entries.slice(0,6).map(entryRow).join("")||'<div class="empty">No entries yet.</div>'}</div>`}
function add(type){addType=type;view="add";render();document.getElementById("app").innerHTML=`<div class="app"><button class="back" onclick="setView('home')">‹ Back</button><h2>Add ${type[0].toUpperCase()+type.slice(1)}</h2><div class="form"><label>Amount (₹)</label><input id="amount" type="number" inputmode="decimal" placeholder="0"><label>Category</label>${type==="income"||type==="expense"?`<select id="cat">${C[type].map(x=>`<option>${x}</option>`).join("")}</select>`:`<input id="person" placeholder="${type==="lent"?"Person you lent to":"Person/company you owe"}">`}<label>${type==="income"||type==="expense"?"Place / Source":"Person / Details"}</label><input id="place" placeholder="Optional"><label>Note</label><textarea id="note" rows="3" placeholder="Optional note"></textarea><label>Date</label><input id="date" type="date" value="${new Date().toISOString().slice(0,10)}">${type==="lent"||type==="debt"?'<label>Due date (optional)</label><input id="due" type="date">':""}<button class="save" onclick="submitEntry()">Save</button></div></div>`}
function submitEntry(){let amount=Number(document.getElementById("amount").value);if(!amount)return alert("Please enter an amount.");let cat=document.getElementById("cat")?.value||addType;let person=document.getElementById("person")?.value||"";let place=document.getElementById("place")?.value||"";let note=document.getElementById("note").value;let date=document.getElementById("date").value;let due=document.getElementById("due")?.value||null;data.entries.unshift({id:Date.now(),type:addType,amount,category:cat,person,place,note,date,dueDate:due});save();setView("home")}
function calendar(){let d=date.toISOString().slice(0,10),es=data.entries.filter(e=>e.date===d);return `<div class="top"><div class="title">Calendar</div><div class="muted">Choose a date to see your activity</div></div><div class="calendar"><input type="date" value="${d}" onchange="date=new Date(this.value+'T12:00:00');render()"></div><div class="card"><h3>${fmtDate(date)}</h3>${es.map(entryRow).join("")||'<div class="empty">No entries for this day.</div>'}</div>`}
function budget(){let me=monthEntries(),we=weekEntries(),ex=me.filter(e=>e.type==="expense").reduce((a,e)=>a+e.amount,0),wx=we.filter(e=>e.type==="expense").reduce((a,e)=>a+e.amount,0),groups={};me.filter(e=>e.type==="expense").forEach(e=>groups[e.category]=(groups[e.category]||0)+e.amount);return `<div class="top"><div class="title">Budget</div><div class="muted">Month & week view</div></div><div class="seg"><button class="${period==="month"?"on":""}" onclick="period='month';render()">Month</button><button class="${period==="week"?"on":""}" onclick="period='week';render()">Week</button></div><div class="card"><label>Monthly expense budget</label><input type="number" inputmode="decimal" value="${data.budget||""}" placeholder="Set budget in ₹" onchange="data.budget=Number(this.value)||0;save();render()"></div><div class="card"><h3>${period==="month"?"This month":"This week"}</h3><div class="row"><span>Expenses</span><b>${money(period==="month"?ex:wx)}</b></div>${data.budget&&period==="month"?`<div class="bar"><i style="width:${Math.min(100,ex/data.budget*100)}%"></i></div><small class="muted">${money(Math.max(0,data.budget-ex))} budget remaining</small>`:""}</div><div class="card"><h3>Monthly expense categories</h3>${Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="row"><span>${esc(k)}</span><b>${money(v)}</b></div>`).join("")||'<div class="empty">No expenses this month.</div>'}</div>`}
function all(){return `<div class="top"><div class="title">All Transactions</div><div class="muted">${data.entries.length} entries</div></div><div class="card">${data.entries.map(entryRow).join("")||'<div class="empty">No entries yet.</div>'}</div>`}
function setView(v){view=v;render()}
render(); if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{})}
